- name: Install ZSH
  become: true
  apt:
    name:
      - zsh
    state: present

- name: Change shell to zsh
  shell: chsh -s $(which zsh)

- name: Check that the .oh-my-zsh exists
  stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: oh_my_stats

- name: Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/PedroS235/ohmyzsh/master/tools/install.sh)"
  when: oh_my_stats.stat.exists == False
  become: true

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
