#!/bin/bash
. ~/.config/HyprV/hyprv.conf

SET_BG = "$HOME/Pictures/Walpapers/v1-background-dark.jpg"

restart_waybar() {
    #restart the waybar
    pkill waybar
    waybar & 
}

set_current_background() {
    swww img $SET_BG
}

switch_keyboard() {
    # TODO: ctrlswap and winaltswap
    hyprctl switchxkblayout $SET_KB next
}

if [[ "$1" == "setbg" ]]; then
    set_current_background
    update_theme
    restart_waybar
elif [[ "$1" == "swkb" ]]; then
    switch_keyboard
    restart_waybar
fi

TOOLTIP='Default Keybinds\n'\
'SUPER + Q = Start Kitty\n'\
'SUPER + F4 = Close Window\n'\
'SUPER + L = Lock Screen\n'\
'SUPER + M = Logout menu\n'\
'SUPER + E = File Manager\n'\
'SUPER + V = Toggle Float\n'\
'SUPER + SPACE = App Launcher\n'\
'SUPER + S = Screenshot\n'\
'SUPER + T = Switch HyprV version\n'\
'ALT + V = Open clipboard manager'

echo '{"tooltip": "'$TOOLTIP'"}'
