# windowrule = float,class:^(1Password)$

# windowrule = float,class:^(org.gnome.Nautilus)$
# windowrule = size 50% 70%,class:^(org.gnome.Nautilus)$

windowrule {
  name = calculator_floating
  match:class = org.gnome.Calculator 
}
