# windowrule = float,class:^(1Password)$

# windowrule = float,class:^(org.gnome.Nautilus)$
# windowrule = size 50% 70%,class:^(org.gnome.Nautilus)$

windowrule = float,class:^(org.gnome.Calculator)$
windowrule = size 10% 30%,class:^(org.gnome.Calculator)$
