- name: "Tmux | Install Tmux"
  become: true
  apt:
    name:
      - tmux
    state: present

- name: "Tmux | Install TPM"
  ansible.builtin.git:
    repo: git clone https://github.com/tmux-plugins/tpm
    depth: 1
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
