import = [
  "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/dracula.toml"
]

[font]
size = 14.0

[font.normal]
family = "GeistMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "GeistMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "GeistMono Nerd Font Mono"
style = "Italic"

[env]
TERM = "xterm-256color"
