import = [
  # "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"
  "~/.config/alacritty/themes/tokyonight.toml"
  # "~/.config/alacritty/themes/dracula.toml"
]

[font]
size = 14.0

[font.normal]
family = "GeistMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "GeistMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "GeistMono Nerd Font Mono"
style = "Italic"

[window]
decorations = "Full"
# startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"
