- name: "Starship | Detecting Installed Starship"
  ansible.builtin.command:
    cmd: which starship
  changed_when: false
  register: starship_cmd
  failed_when: false

- name: "Starship | Register starship status installed"
  ansible.builtin.set_fact:
    starship_is_installed: true
  when: nala_cmd.stdout|length > 0

- name: "Starship | Register starship status not installed"
  ansible.builtin.set_fact:
    starship_is_installed: false
  when: nala_cmd.stdout|length == 0

- name: "Starship | Install Starship"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/PedroS235/ohmyzsh/master/tools/install.sh)"
  become: true
  when: not starship_is_installed
